<?php
namespace ApiResponse\Response;

class Response
{
    const HTTP_CONTINUE = 100;
    const HTTP_SWITCHING_PROTOCOLS = 101;
    const HTTP_PROCESSING = 102;
    const HTTP_EARLY_HINTS = 103;
    const HTTP_OK = 200;
    const HTTP_CREATED = 201;
    const HTTP_ACCEPTED = 202;
    const HTTP_NON_AUTHORITATIVE_INFORMATION = 203;
    const HTTP_NO_CONTENT = 204;
    const HTTP_RESET_CONTENT = 205;
    const HTTP_PARTIAL_CONTENT = 206;
    const HTTP_MULTI_STATUS = 207;
    const HTTP_ALREADY_REPORTED = 208;
    const HTTP_IM_USED = 226;
    const HTTP_MULTIPLE_CHOICES = 300;
    const HTTP_MOVED_PERMANENTLY = 301;
    const HTTP_FOUND = 302;
    const HTTP_SEE_OTHER = 303;
    const HTTP_NOT_MODIFIED = 304;
    const HTTP_USE_PROXY = 305;
    const HTTP_RESERVED = 306;
    const HTTP_TEMPORARY_REDIRECT = 307;
    const HTTP_PERMANENTLY_REDIRECT = 308;
    const HTTP_BAD_REQUEST = 400;
    const HTTP_UNAUTHORIZED = 401;
    const HTTP_PAYMENT_REQUIRED = 402;
    const HTTP_FORBIDDEN = 403;
    const HTTP_NOT_FOUND = 404;
    const HTTP_METHOD_NOT_ALLOWED = 405;
    const HTTP_NOT_ACCEPTABLE = 406;
    const HTTP_PROXY_AUTHENTICATION_REQUIRED = 407;
    const HTTP_REQUEST_TIMEOUT = 408;
    const HTTP_CONFLICT = 409;
    const HTTP_GONE = 410;
    const HTTP_LENGTH_REQUIRED = 411;
    const HTTP_PRECONDITION_FAILED = 412;
    const HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
    const HTTP_REQUEST_URI_TOO_LONG = 414;
    const HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
    const HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    const HTTP_EXPECTATION_FAILED = 417;
    const HTTP_I_AM_A_TEAPOT = 418;
    const HTTP_MISDIRECTED_REQUEST = 421;
    const HTTP_UNPROCESSABLE_ENTITY = 422;
    const HTTP_LOCKED = 423;
    const HTTP_FAILED_DEPENDENCY = 424;

    const HTTP_VALID_CODES = [
      self::HTTP_SWITCHING_PROTOCOLS,
      self::HTTP_CONTINUE,
      self::HTTP_PROCESSING,
      self::HTTP_EARLY_HINTS,
      self::HTTP_OK,
      self::HTTP_CREATED,
      self::HTTP_ACCEPTED,
      self::HTTP_NON_AUTHORITATIVE_INFORMATION,
      self::HTTP_NO_CONTENT,
      self::HTTP_RESET_CONTENT,
      self::HTTP_PARTIAL_CONTENT,
      self::HTTP_MULTI_STATUS,
      self::HTTP_ALREADY_REPORTED,
      self::HTTP_IM_USED,
      self::HTTP_MULTIPLE_CHOICES,
      self::HTTP_MOVED_PERMANENTLY,
      self::HTTP_FOUND,
      self::HTTP_SEE_OTHER,
      self::HTTP_NOT_MODIFIED,
      self::HTTP_USE_PROXY,
      self::HTTP_RESERVED,
      self::HTTP_TEMPORARY_REDIRECT,
      self::HTTP_PERMANENTLY_REDIRECT,
      self::HTTP_BAD_REQUEST,
      self::HTTP_UNAUTHORIZED,
      self::HTTP_PAYMENT_REQUIRED,
      self::HTTP_FORBIDDEN,
      self::HTTP_NOT_FOUND,
      self::HTTP_METHOD_NOT_ALLOWED,
      self::HTTP_NOT_ACCEPTABLE,
      self::HTTP_PROXY_AUTHENTICATION_REQUIRED,
      self::HTTP_REQUEST_TIMEOUT,
      self::HTTP_CONFLICT,
      self::HTTP_GONE,
      self::HTTP_LENGTH_REQUIRED,
      self::HTTP_PRECONDITION_FAILED,
      self::HTTP_REQUEST_ENTITY_TOO_LARGE,
      self::HTTP_REQUEST_URI_TOO_LONG,
      self::HTTP_UNSUPPORTED_MEDIA_TYPE,
      self::HTTP_REQUESTED_RANGE_NOT_SATISFIABLE,
      self::HTTP_EXPECTATION_FAILED,
      self::HTTP_I_AM_A_TEAPOT,
      self::HTTP_MISDIRECTED_REQUEST,
      self::HTTP_UNPROCESSABLE_ENTITY,
      self::HTTP_LOCKED,
      self::HTTP_FAILED_DEPENDENCY,
    ];
}